# Generated by Django 6.1 on 2026-08-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APICustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'is_active'], name='location_ap_email_6f7ebc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cell')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(db_index=True, help_text='e.g., https://myapp.com or http://localhost:3000', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_origins', to='location.apicustomer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'is_active'], name='location_al_custome_4adb79_idx'), models.Index(fields=['origin'], name='location_al_origin_608224_idx')],
                'unique_together': {('customer', 'origin')},
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Production Key, Testing Key', max_length=100)),
                ('key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(db_index=True, editable=False, max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='location.apicustomer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'is_active'], name='location_ap_custome_8910da_idx'), models.Index(fields=['key_prefix'], name='location_ap_key_pre_b3f947_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('origin', models.CharField(db_index=True, max_length=255)),
                ('request_count', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to='location.apicustomer')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['customer', 'date'], name='location_ap_custome_981b89_idx'), models.Index(fields=['endpoint'], name='location_ap_endpoin_ab6c1f_idx'), models.Index(fields=['status_code'], name='location_ap_status__2a9c8a_idx'), models.Index(fields=['date'], name='location_ap_date_0a00e8_idx'), models.Index(fields=['customer', 'date', 'endpoint'], name='location_ap_custome_e66f7c_idx'), models.Index(fields=['customer', 'date', 'endpoint', 'status_code'], name='location_ap_custome_ec4122_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'name'], name='location_pr_country_6cae21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'name'], name='location_di_provinc_c95764_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'province')},
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['district', 'name'], name='location_se_distric_827894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'district')},
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['sector', 'name'], name='location_ce_sector__3c9b87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('name', 'sector')},
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['cell', 'name'], name='location_vi_cell_id_d2c108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'cell')},
        ),
    ]
