# Generated by Django 5.1.3 on 2025-05-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.sector'),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='village',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cell'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'province')},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'cell')},
        ),
    ]
