# Generated by Django 6.1 on 2026-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_apicustomer_apikey_allowedorigin_apiusage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['endpoint'], name='location_ap_endpoin_ab6c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['status_code'], name='location_ap_status__2a9c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['date'], name='location_ap_date_0a00e8_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['customer', 'date', 'endpoint'], name='location_ap_custome_e66f7c_idx'),
        ),
    ]
