"""
Django settings for rwanda_admin_api project.
Generated by 'django-admin startproject' using Django 5.1.3.
"""

import os
import sys
import dj_database_url # type: ignore
from pathlib import Path
from dotenv import load_dotenv # type: ignore

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-d*(zv3ybisw^um6ima*)7=c@78c2h*2$xx67$h8b-bz_^6n&r&')

# Redis Configuration - Build from components
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')
REDIS_DB = os.environ.get('REDIS_DB', '1')

# Build REDIS_URL
if REDIS_PASSWORD:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    
# Set environment variable for consistency
os.environ['REDIS_URL'] = REDIS_URL

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'rwanda-administrative-structure-api.onrender.com',
    '.onrender.com',  # This wildcard allows all Render subdomains
]
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "location",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "corsheaders",  # Add this for API access from different origins
    #'drf-yasg',
    'django_extensions',
    'debug_toolbar',
    'silk',
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'silk.middleware.SilkyMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this for static files
    "corsheaders.middleware.CorsMiddleware",  # Add this early
    "location.middleware.APIAuthenticationMiddleware",  # Add this first
    "location.middleware.OriginRestrictionMiddleware",  # Add this second
    "location.middleware.UsageTrackingMiddleware", 
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.cache.FetchFromCacheMiddleware',
]

MIDDLEWARE.insert(0, 'django.middleware.gzip.GZipMiddleware')
ROOT_URLCONF = "rwanda_admin_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rwanda_admin_api.wsgi.application"

# Database - Use PostgreSQL with DATABASE_URL from Render
# The if condition allows local development with hardcoded values
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'wars_db'),
            'USER': os.environ.get('DB_USER', 'wars_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'wars_password_2024'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS':{
                'connect_timeout':5,
                'options': '-c statement_timeout=30s',
            },
            'CONN_MAX_AGE':600, # Keep connection alive for 10 minutes
        }
    }

# Caching

if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
                'CONNECTION_POOL_CLASS_KWARGS': {
                    'max_connections': 50,
                    'timeout': 20,
                },
                'MAX_CONNECTIONS': 50,
                'PICKLE_VERSION': -1,
            },
            'KEY_PREFIX': 'rwanda_api',
            'TIMEOUT': 3600,  # 1 hour default cache
        }
    }
else:
    # Fallback to local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
    
    
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': REDIS_PASSWORD,
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'MAX_CONNECTIONS': 50,
            'PICKLE_VERSION': -1,
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'rwanda_api',
        'TIMEOUT': 3600,
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# CORS Configuration (for frontend access)
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in development

#Enable query logging in development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
        'SHOW_COLLAPSED': True,
        'SQL_WARNING_THRESHOLD': 100,  # Highlight queries > 100ms
    }
    
    # ✅ Combine both logging configurations
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': 'api_performance.log',
                'formatter': 'verbose',
            },
            'perf_file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': 'api_performance.log',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'api.middleware': {
                'handlers': ['perf_file'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.db.backends': {
                'level': 'DEBUG' if DEBUG else 'INFO',
                'handlers': ['console'],
                'propagate': False,
            },
            'django.request': {
                'handlers': ['file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
    
# Silk Performance Profiling
SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_MAX_RECORDED_REQUESTS = 1000
SILKY_MAX_RESPONSE_BODY_SIZE = 1024

# Health Check URL
HEALTH_CHECK_URL = '/health/'

# Fix: Handle empty or missing CORS_ALLOWED_ORIGINS
if not DEBUG:
    cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    if cors_origins:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',') if origin.strip()]
    else:
        # Default to your Render URL if none provided
        CORS_ALLOWED_ORIGINS = [
            'https://rwanda-administrative-structure-api.onrender.com',
            'http://localhost:3000',
            'http://localhost:5173', # Vite Dev Server
            'http://127.0.0.1:8000'
        ]
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings (optional)
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_EXPOSE_HEADERS = ['X-Response-Time']  # Expose performance headers


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Kigali"  # Set to Rwanda time
USE_I18N = True
USE_TZ = True

# Add Internal APIs
INTERNAL_APIS =[
    '127.0.0.1',
    'localhost'
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Stripe Secret Key
STRIPE_SECRET_KEY=""

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Security settings for production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
    SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
    SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
    
    

# Performance Monitoring
PERFORMANCE_MONITORING = {
    'SLOW_REQUEST_THRESHOLD': 1000,  # Log requests > 1 second
    'SLOW_QUERY_THRESHOLD': 100,     # Log queries > 100ms
    'ENABLE_REQUEST_LOGGING': True,
}

# Database connection pool settings
DATABASE_POOL = {
    'MAX_CONNECTIONS': 20,
    'MIN_CONNECTIONS': 5,
    'IDLE_TIMEOUT': 600,
}

# Cache settings
CACHE_TTL = {
    'STATIC_DATA': 86400,   # 24 hours for static data
    'DYNAMIC_DATA': 3600,   # 1 hour for dynamic data
    'USER_DATA': 300,       # 5 minutes for user-specific data
}

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'rwanda_api'

SILKY_PYTHON_PROFILER = False  # ✅ Disable Silk's profiler
SILKY_RECORD_REQUESTS = True   # Keep request recording